FROM dcapwell/hadoop-base:0.2

RUN mkdir -p /opt/spark

RUN cd /opt/spark && wget 'http://d3kbcqa49mib13.cloudfront.net/spark-1.0.1-bin-hadoop2.tgz' && tar zxvf spark-1.0.1-bin-hadoop2.tgz && rm spark-1.0.1-bin-hadoop2.tgz
